# Generated by Django 3.2.7 on 2021-09-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
